version: '3.7'
services:

  php-fpm:
    image: localhost/calculator-form-php-fpm:latest
    restart: always
    container_name: calculator-form-php-fpm
    volumes:
      - ./:/var/www/html

  nginx:
    image: localhost/calculator-form-nginx:latest
    restart: always
    container_name: calculator-form-nginx
    ports:
      - ${APP_WEB_PORT}:80
    environment:
      PHP_UPSTREAM_CONTAINER: php-fpm
      PHP_UPSTREAM_PORT: 9000
    depends_on:
      - php-fpm
    volumes:
      - ./web:/var/www/html/web